[profile.default]
solc_version = '0.8.27'
src = 'src'
out = 'build'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./"}]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
84532 = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "$ETHERSCAN_API_KEY" }
84532 = { key = "$BASESCAN_API_KEY", url = "https://api-sepolia.basescan.org/api" }
